os: linux

language: python

go:
  - "1.11"

python:
  -"3.6"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
    packages:
      - squashfs
    update: true

sudo: required

matrix:
  include:
    - python: "3.6"

before_install:
  - sudo chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh

install: true

before_script:
  - which singularity
  - singularity pull --help
#  - singularity pull -n local.img shub://DeepLearnPhysics/larcv2-singularity:ub18.04-cuda100-py3-pytorch1.1.0-scn
#  - sudo singularity build local.img .travis/Singularity.ub18.04-cuda100-py3-pytorch1.1.0-scn
  - singularity pull --allow-unauthenticated local.simg library://temigo/default/lartpc_mlreco3d:sha256.2f2b3011371e109db83e21b556d3d82f21b639acad4a412589429e9b9abc53de
  - ls
  - singularity exec local.simg bash

script:
  - pytest
